name: Build OpenCV JavaDocs

on:
  schedule:
    - cron: '30 3 * * *'  

jobs:
  build-javadoc:
    name: JavaDocs ${{ matrix.branch }}
    runs-on: ubuntu-22.04
    container:
      image: quay.io/ivan_avdeev/opencv_test:opencv-docs-22.04-jdk-20250526
      options: --user ci
    strategy:
      matrix:
        branch: [4.x, 5.x]
    env:
      OPENCV_SRC: /home/ci/opencv
      OPENCV_BUILD: /home/ci/opencv-build
      JAVA_DOC: /home/ci/opencv-build/doc/doxygen/html/javadoc
    steps:
      - name: Checkout OpenCV
        run: |
          git clone --branch ${{ matrix.branch }} https://github.com/opencv/opencv.git $OPENCV_SRC
      - name: Checkout OpenCV Contrib
        run: |
          git clone --branch ${{ matrix.branch }} https://github.com/opencv/opencv_contrib.git /home/ci/opencv_contrib

      - name: Configure CMake (generate Java sources)
        run: |
          mkdir -p $OPENCV_BUILD
          cd $OPENCV_BUILD
          cmake -DBUILD_SHARED_LIBS=OFF \
                -DBUILD_opencv_java=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DOPENCV_EXTRA_MODULES_PATH=/home/ci/opencv_contrib/modules \
                -DANT_EXECUTABLE=/usr/bin/ant \
                $OPENCV_SRC

      - name: Build Java Bindings (to generate sources)
        run: |
          cd $OPENCV_BUILD
          make -j2

      - name: Generate Javadoc using Ant
        run: |
          cd $OPENCV_BUILD/modules/java/jar/opencv
          ant javadoc

      - name: Archive Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: opencv-javadoc-${{ matrix.branch }}
          path: /home/ci/opencv-build/doc/doxygen/html/javadoc
